[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_ignores = true
warn_redundant_casts = true

# ---- Ruff（lint + format + import 並べ替え）----
[tool.ruff]
line-length = 88

[tool.ruff.lint]
# E=pycodestyle, F=pyflakes, I=import（=isort相当）
select = ["E", "F", "I"]
ignore = ["E203"]

[tool.ruff.format]
# 既定がBlack互換
