name: ci-ruff
on: [push, pull_request]

jobs:
  qa-ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Install dev deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt

      # ---- Formatter（Black互換）
      - name: Ruff format (check)
        run: ruff format --check .

      # ---- Lint + import 並べ替え (I) を自動修正
      - name: Ruff check (fix)
        run: ruff check . --fix --exit-non-zero-on-fix

      # ---- Type check
      - name: mypy
        run: mypy .
